# Generated by Django 5.1.1 on 2024-10-26 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('otp', models.CharField(default='225035', max_length=6)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiresAt', models.DateTimeField(default=datetime.datetime(2024, 10, 26, 13, 50, 17, 15139))),
            ],
        ),
    ]
