# Generated by Django 5.1.1 on 2024-10-26 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiresAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 14, 20, 2, 189475)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default='865006', max_length=6),
        ),
    ]
