# Generated by Django 5.1.1 on 2024-10-26 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_otptoken_expiresat_alter_otptoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiresAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 14, 23, 52, 849326)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default='414085', max_length=6),
        ),
    ]
