# Generated by Django 5.1.1 on 2024-10-26 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_otptoken_expiresat_alter_otptoken_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiresAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 14, 26, 33, 3418)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default='496886', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
