# Generated by Django 5.1.1 on 2024-10-26 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_otptoken_expiresat_alter_otptoken_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiresAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 14, 29, 40, 760151)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default='432539', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
