# Generated by Django 5.1.1 on 2024-10-27 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_otptoken_expiresat_alter_otptoken_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiresAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 10, 35, 8, 36563)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp',
            field=models.CharField(default='296242', max_length=6),
        ),
    ]
